<?php

namespace App\Repositories;

use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use App\Repositories\articleRepository;
use App\Entities\Article;
use App\Validators\ArticleValidator;
use DB;

/**
 * Class ArticleRepositoryEloquent.
 *
 * @package namespace App\Repositories;
 * sql 문 작성 하는곳?
 *
 */
class ArticleRepositoryEloquent extends BaseRepository implements ArticleRepository
{
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return Article::class;
    }
    public function test(){

    }

    public function update(array $attributes, $idx)
    {

        return  DB::update('update test.articles set title = ? , content = ?  where idx = ?',[$attributes['title'],$attributes['content'],$idx]);; // TODO: Change the autogenerated stub
    }

    public  function delete($idx)
    {
        return  DB::delete ('DELETE FROM test.articles  where idx = ?',[$idx]); // TODO: Change the autogenerated stub
    }

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }


}
